name: 'build'

on:
  pull_request:
  workflow_dispatch:

jobs:
  tagged-release:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: |
          npm install

      - name: Prebuild App (generate native files)
        run: npx expo prebuild --clean

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon

      - name: Build for Web
        run: |
          npm run build:web
