name: 'Build and Release'

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # install-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@v3
  #     - name: Install npm dependencies
  #       run: |
  #         npm install
  #     # run tests here eventually

  build-and-release:
    name: 'Build and Release'
    # needs: install-and-test
    runs-on: 'ubuntu-latest'
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: Install Dependencies
        run: |
          npm install

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            semantic-release-expo

      - name: Build App
        run: |
          eas build --local \
            --non-interactive \
            --output=./conbingo.aab \
            --platform=android \
            --profile=production

      - name: Sign App Bundle
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed App Bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      # - name: Attach Artifact to Release
      #   run: |
      #     gh release upload ${{ steps.semantic-release.outputs.new_release_git_tag }} ./app-build/*.aab --clobber
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload App to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
          packageName: com.conbingo
          releaseFiles: ./*.aab
          track: internal
          status: draft
          inAppUpdatePriority: 2

      - name: Build for Web
        run: |
          npm run build:web

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
